Import('env')
import gslab_scons as gs

build  = env['CONFIG']['global']['build']['estimation']
source = env['CONFIG']['global']['source']['estimation']
input  = env['CONFIG']['global']['input']

env.BuildStata(target  = ['#%s/data.txt'          % build],
               source  = ['#%s/iv_regressions.do' % source,
                          '#%s/qob1.dta'          % input])


env.Install('#release', '#%s/' % build)
