Import('env')

build  = env['CONFIG']['global']['build']['descriptive']
source = env['CONFIG']['global']['source']['descriptive']

env.BuildStata(target  = ['#%s/plot.eps'                        % build,
                          '#%s/table.txt'                       % build],
               source  = ['#%s/illustrate_research_design.do'   % source,
                          '#%s/data.txt'                        % source])

env.Install('#release', '#%s/' % build)
