Import('env')

build  = env['CONFIG']['global']['build']['descriptive']
source = env['CONFIG']['global']['source']['descriptive']
input  = env['CONFIG']['global']['input']

env.BuildStata(target  = ['#%s/education_by_yob_qob.eps'        % build,
                          '#%s/education_by_yob_qob.png'        % build,
                          '#%s/education_by_qob_lessthan12.eps' % build,
                          '#%s/education_by_qob_lessthan12.png' % build,
                          '#%s/education_by_qob_12plus.eps'     % build,
                          '#%s/education_by_qob_12plus.png'     % build],
               source  = ['#%s/illustrate_research_design.do'   % source,
                          '#%s/qob1.dta'                        % input])

env.Install('#release', '#%s/' % build)
